<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
    @page { margin: 40px 45px; }
    * { font-family: DejaVu Sans, sans-serif; }
    body { color: #1e293b; font-size: 11px; }

    .letterhead { text-align: center; border-bottom: 3px solid #1a3c5e; padding-bottom: 12px; margin-bottom: 6px; }
    .letterhead h1 { color: #1a3c5e; font-size: 20px; margin: 0; }
    .letterhead .sub { color: #64748b; font-size: 11px; margin-top: 2px; }
    .letterhead .report-title { color: #e8a020; font-size: 14px; font-weight: bold; margin-top: 8px; text-transform: uppercase; letter-spacing: 1px; }

    .meta { text-align: center; color: #64748b; font-size: 10px; margin-bottom: 16px; }

    table { width: 100%; border-collapse: collapse; }
    th { background: #1a3c5e; color: #fff; text-align: left; padding: 7px 10px; font-size: 10px; text-transform: uppercase; }
    th.amt, td.amt { text-align: right; }
    td { padding: 5px 10px; border-bottom: 1px solid #e2e8f0; }

    .section-head td { background: #dcfce7; color: #15803d; font-weight: bold; font-size: 12px; text-transform: uppercase; }
    .section-head.exp td { background: #fee2e2; color: #b91c1c; }

    .group td { background: #f1f5f9; font-weight: bold; }
    .child td { color: #475569; }
    .child .name { padding-left: 26px; }

    .total-row td { border-top: 2px solid #16a34a; font-weight: bold; color: #15803d; font-size: 12px; }
    .total-row.exp td { border-top: 2px solid #dc2626; color: #b91c1c; }

    .net-row td { border-top: 3px double #1a3c5e; background: #f0f4f8; font-weight: bold; color: #1a3c5e; font-size: 13px; }

    .footer { position: fixed; bottom: -20px; left: 0; right: 0; text-align: center; color: #94a3b8; font-size: 9px; }
</style>
</head>
<body>

<div class="letterhead">
    <h1>{{ $churchName }}</h1>
    <div class="sub">Financial Management System</div>
    <div class="report-title">Financial Report</div>
</div>

<div class="meta">
    Period: {{ \Carbon\Carbon::parse($from)->format('M d, Y') }} &nbsp;—&nbsp; {{ \Carbon\Carbon::parse($to)->format('M d, Y') }}
    &nbsp;|&nbsp; Generated: {{ $generatedAt }}
</div>

<table>
    <thead>
        <tr>
            <th style="width:70px;">Ref</th>
            <th>Account</th>
            <th class="amt" style="width:130px;">Amount (GHS)</th>
        </tr>
    </thead>
    <tbody>
        <!-- INCOME -->
        <tr class="section-head"><td colspan="3">Income — Inflows</td></tr>
        @foreach($income as $group)
        <tr class="group">
            <td>{{ $group->ref }}</td>
            <td>{{ $group->name }}</td>
            <td class="amt">{{ number_format($group->total, 2) }}</td>
        </tr>
        @foreach($group->children as $child)
        <tr class="child">
            <td>{{ $child->ref }}</td>
            <td class="name">{{ $child->name }}</td>
            <td class="amt">{{ number_format($child->total, 2) }}</td>
        </tr>
        @endforeach
        @endforeach
        <tr class="total-row">
            <td colspan="2">TOTAL INCOME</td>
            <td class="amt">{{ number_format($totalIncome, 2) }}</td>
        </tr>

        <!-- EXPENDITURE -->
        <tr class="section-head exp"><td colspan="3">Expenditure — Outflows</td></tr>
        @foreach($expense as $group)
        <tr class="group">
            <td>{{ $group->ref }}</td>
            <td>{{ $group->name }}</td>
            <td class="amt">{{ number_format($group->total, 2) }}</td>
        </tr>
        @foreach($group->children as $child)
        <tr class="child">
            <td>{{ $child->ref }}</td>
            <td class="name">{{ $child->name }}</td>
            <td class="amt">{{ number_format($child->total, 2) }}</td>
        </tr>
        @endforeach
        @endforeach
        <tr class="total-row exp">
            <td colspan="2">TOTAL EXPENDITURE</td>
            <td class="amt">{{ number_format($totalExpense, 2) }}</td>
        </tr>

        <!-- NET -->
        <tr class="net-row">
            <td colspan="2">NET BALANCE (Inflows − Outflows)</td>
            <td class="amt">{{ number_format($netBalance, 2) }}</td>
        </tr>
    </tbody>
</table>

<div class="footer">
    {{ $churchName }} — Financial Report — Generated by the Church Management System
</div>

</body>
</html>